import { Inter } from "next/font/google";
import "../styles/globals.css";
import AppHeader from "./AppHeader";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
  return (
    <div className={inter.className} >
      <main className="flex min-h-screen flex-col px-8 py-4 w-full items-center gap-8 bg-gradient-to-b from-secondary-800 to-black">
        <AppHeader></AppHeader>
        {children}
      </main>
    </div>
  );
}
export default Layout;